columns_to_use : [
  'target',
  'TaxaDeUtilizacaoDeLinhasNaoGarantidas',
  'Idade',
  'NumeroDeVezes30-59DiasAtrasoNaoPior',
  'TaxaDeEndividamento',
  'RendaMensal',
  'NumeroDeLinhasDeCreditoEEmprestimosAbertos',
  'NumeroDeVezes90DiasAtraso',
  'NumeroDeEmprestimosOuLinhasImobiliarias',
  'NumeroDeVezes60-89DiasAtrasoNaoPior',
  'NumeroDeDependentes'
]

mlflow_uri : 'http://localhost:5000'
mlflow_experiment_name : 'prob_loan'

target_column : 'target'

test_size : 0.33

random_state : 42

imputer_variables: ['RendaMensal', 'NumeroDeDependentes']

discretiser_variables: ['TaxaDeUtilizacaoDeLinhasNaoGarantidas', 'TaxaDeEndividamento', 'RendaMensal']

model_name: 'model.joblib'